### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by marsamos**
Changes in grimme D3, now working, hopefully, for some of the qe input_dft short names. added example and documentation in INPUT_PW.def.

### CODE REVIEW

**Comment by pietrodelugas** [comment]
ok grazie  Layla. 
 I will take it from here and merge on develop in gitlab.

**Comment by giannozz** [comment]
I previously made changes to INPUT_PW.def that must be kept.

**Comment by pietrodelugas** [comment]
Ok. Those changes seems to be _orthogonal_ to these ones without any conflict. I will rebase to the current develop and check before merging anyway.

**Comment by pietrodelugas** [comment]
The pull request has been moved to gitlab 
We can close it here.

**Pull request closed without merging**
